# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise32-cloudimages"
  config.vm.box_url = "precise-server-cloudimg-i386-vagrant-disk1.box

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  loadbalancer.vm.provision "shell", path: "baseline.sh"
end
